---
- hosts: mastodon
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: upgrade Ruby
    import_tasks: tasks/hs_ruby.yml

  - name: drop old Ruby version
    become: yes
    file:
        path: /home/pacs/{{pac}}/users/{{user}}/.rbenv/versions/3.0.3
        state: absent

  - name: checkout specific mastodon release
    become: yes
    shell: |
       # checkout specific release
       git fetch && git checkout "{{mastodon_release}}" || exit -1
    args:
        executable: /bin/bash
        chdir: "/home/pacs/{{pac}}/users/{{user}}/live"

  - name: bundle install
    become: yes
    shell: |
       . ~/.profile
       cd ~/live
       bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}"

  - name: yarn install
    become: yes
    shell: |
       . ~/.profile
       cd ~/live
       yarn install --pure-lockfile || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}"

  - name: pre deployment database migrations
    become: yes
    shell: |
       . ~/.profile
       cd ~/live
       SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate || exit -1
    args:
        executable: /bin/bash
        chdir: "/home/pacs/{{pac}}/users/{{user}}"

  - name: initialise assets
    become: yes
    shell: |
       . ~/.profile
       cd ~/live
       RAILS_ENV=production bundle exec rails assets:precompile || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}"

  - name: restart the services
    become: yes
    shell: |
       ~/bin/restart.sh || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/live"

  - name: finish database migrations
    become: yes
    shell: |
       . ~/.profile
       cd ~/live
       RAILS_ENV=production bundle exec rails db:migrate || exit -1
    args:
        executable: /bin/bash
        chdir: "/home/pacs/{{pac}}/users/{{user}}"

  - name: restart the services again
    become: yes
    shell: |
       ~/bin/restart.sh || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/live"
